-- Active: 1772562537961@@127.0.0.1@3306
ALTER TABLE frutarias DROP COLUMN endereco;
ALTER TABLE frutarias DROP COLUMN nome;
ALTER TABLE frutarias ADD COLUMN nome DEFAULT "" NOT NULL;
ALTER TABLE frutarias ADD COLUMN CNPJ DEFAULT 0 NOT NULL; 